version: "3.8"
services:
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD} 
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
